baseURL = "https://invisible-voice.com/"
languageCode = "en-gb"
title = "Invisible Vocals"
plugins_css = ["custom"]
timeout = "3m"
ignoreErrors = ["error-remote-getjson"]
cacheDir = "/home/orange/Projects/invisible-rosetta/hugo/cache"
[outputs]
  home = ["HTML", "json"]
  page = ["HTML", "json"]
  section = ["JSON"]
[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.getresource]
    dir = ':cacheDir/:project'
    maxAge = -1
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.modules]
    dir = ':cacheDir/modules'
    maxAge = -1
